#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagement.Views.Contact
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ContactManagement;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Contact/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<ContactManagement.ViewModel.ContactListViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Contact\Index.cshtml"
  
    ViewBag.Title = "Contact List";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Contact List</h2>\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" action=\"/Contact/Index\"");

WriteLiteral(" method=\"GET\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"name\"");

WriteLiteral(">Name</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"name\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" placeholder=\"Name\"");

WriteAttribute("value", Tuple.Create(" value=\"", 444), Tuple.Create("\"", 469)
            
            #line 13 "..\..\Views\Contact\Index.cshtml"
                         , Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(ViewBag.NameParm
            
            #line default
            #line hidden
, 452), false)
);

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"mobile\"");

WriteLiteral(">Mobile</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"mobile\"");

WriteLiteral(" name=\"mobile\"");

WriteLiteral(" placeholder=\"eg.0450 232333\"");

WriteAttribute("value", Tuple.Create(" value=\"", 693), Tuple.Create("\"", 720)
            
            #line 17 "..\..\Views\Contact\Index.cshtml"
                                       , Tuple.Create(Tuple.Create("", 701), Tuple.Create<System.Object, System.Int32>(ViewBag.MobileParm
            
            #line default
            #line hidden
, 701), false)
);

WriteLiteral(">\r\n            </div>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral("/>\r\n        </form>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnNewContact\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span>New Contact\r\n            </button>\r\n        </p>\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n            <tr>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Mobile));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 44 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th>\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\Contact\Index.cshtml"
               Write(Html.DisplayNameFor(model => model.PhotoPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </th>\r\n                <th></th>\r\n            </tr>\r\n\r\n");

            
            #line 52 "..\..\Views\Contact\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Contact\Index.cshtml"
             foreach (var item in Model)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 56 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 59 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 62 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Mobile));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 65 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 68 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

            
            #line 71 "..\..\Views\Contact\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Contact\Index.cshtml"
                         if (!string.IsNullOrEmpty(item.PhotoPath))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2700), Tuple.Create("\"", 2734)
            
            #line 73 "..\..\Views\Contact\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2706), Tuple.Create<System.Object, System.Int32>(Url.Content(item.PhotoPath)
            
            #line default
            #line hidden
, 2706), false)
);

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" width=\"152\"");

WriteLiteral(" height=\"118\"");

WriteLiteral(" />\r\n");

            
            #line 74 "..\..\Views\Contact\Index.cshtml"

                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 79 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.ActionLink("Edit", "Edit", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                        ");

            
            #line 80 "..\..\Views\Contact\Index.cshtml"
                   Write(Html.ActionLink("Delete", "Delete", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 83 "..\..\Views\Contact\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </table>\r\n    </div>\r\n\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(\"#btnNewContact\").click(function () {\r\n            location.href = \'" +
"");

            
            #line 94 "..\..\Views\Contact\Index.cshtml"
                        Write(Url.Action("Create","Contact"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        });\r\n    </script>\r\n\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
